In [2]:
import numpy as np

x = np.float32(3.1415)
type(x)

numpy.float32

In [3]:
x

3.1415

In [4]:
x = np.int_(8675309)
x

8675309

In [5]:
x = np.float64(3.1415)
x

3.1415

In [6]:
y = np.float32(3.1415)
type(y)

numpy.float32

In [7]:
x==y

False

In [8]:
x==np.float64(y)

False

In [9]:
x = np.int_(8675309)
type(x)

numpy.int64

In [10]:
np.array([1,2,3], dtype='uint')

array([1, 2, 3], dtype=uint64)

In [12]:
np.zeros( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(2,3,0.1, dtype='float')

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [15]:
x.shape=(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
x.shape=(2,3,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [20]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [22]:
x = np.arange(10)
x[2:5]

array([2, 3, 4])

In [23]:
x[:-7]

array([0, 1, 2])

In [24]:
x[1:7:2]

array([1, 3, 5])

In [25]:
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
np.reshape(np.arange(1,13), (3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
x[1]

array([5, 6, 7, 8])

In [79]:
x[:,(1,3)]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [80]:
x[(0,2),(1,3)]

array([ 2, 12])

In [28]:
x = np.arange(10)
x[ x>7 ]

array([8, 9])

In [29]:
x[ (x>7) or (x<2) ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [30]:
x = np.arange(10)
# Numpy's any and all largely replicate Python's built-in any and all...
np.all(x>7)

False

In [31]:
np.any(x>7)

True

In [32]:
np.any([x>7,x<2])

True

In [34]:
#...except numpy.any and numpy.all also support acting "along" an axis
np.any([x>7,x<2], axis=1)

array([ True,  True])

In [35]:
np.any([x>7,x<2], axis=0)

array([ True,  True, False, False, False, False, False, False,  True,
        True])

In [36]:
x = np.arange(10)
x[np.logical_and(x>3,x<7)]

array([4, 5, 6])

In [37]:
np.logical_or(x<3,x>7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [38]:
np.logical_xor(x<3,x>7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [39]:
np.logical_not(x>3)

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [41]:
# Generate a 2-by-3 matrix of Unif(0,1).
# numpy.random.random() generates a single draw from unif(0,1), like Python's random.random()
np.random.random( (2,3) )

array([[0.28406622, 0.67692514, 0.34852948],
       [0.45370691, 0.22849168, 0.25161225]])

In [42]:
np.random.normal( 0,1,20 ) # 20 specifies a number of draws to generate

array([ 0.35706036,  1.63093662, -0.18249649,  0.97262028,  0.75831351,
        1.00935184,  0.14421419,  2.04360733, -0.75213557,  0.24101392,
        0.8717613 , -1.50819317,  1.07325642, -0.12529381,  0.35963005,
       -0.33870658, -0.55500145,  0.49382033, -1.79190304,  0.18007676])

In [44]:
# This code is equivalent to np.random.random( (2,4) )
np.random.uniform( 0,1, (2,4)) # (2,4) is a size argument, specifying to generate a 2-by-4 array of unif(0,1)

array([[0.11216306, 0.58985929, 0.52171791, 0.25117251],
       [0.08950748, 0.41573509, 0.22913754, 0.24013596]])

In [45]:
x = np.arange( 1, 11 )
for _ in range(5):
    # x/float(sum(x)) is a vector that sums to 1; specifies the probability of choosing each elmt of x
    print( np.random.choice(x, 5, False, x/float(sum(x)) ) )

[10  8  3  6  5]
[ 8 10  4  7  9]
[ 8  5 10  9  4]
[ 4  9  5 10  8]
[ 8  5 10  7  6]


In [46]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
np.random.shuffle(x)
print( x ) # np.random.shuffle has a sideeffect.

[0 7 1 4 3 8 2 6 9 5]


In [48]:
print( np.random.permutation(x) )

[7 1 6 3 2 5 8 9 0 4]


In [49]:
print( x ) # np.random.permutation(x) didn't change x.

[0 7 1 4 3 8 2 6 9 5]


In [82]:
A = np.reshape(np.arange(1,13), (3,4))
x = np.ones(4)
A*x

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [40]:
np.random.random( (2,3) )

array([[0.13328843, 0.42774637, 0.85257207],
       [0.04429909, 0.48400179, 0.6621342 ]])

In [50]:
x = np.random.normal(0, 1, 100) # Generate 100 draws from a normal
np.mean(x), np.median(x), np.std(x)

(-0.1853617285700267, -0.2713782258839418, 0.9343687096356638)

In [51]:
np.min(x), np.max(x), np.ptp(x) # ptp is max-min

(-1.982811806043661, 2.3036651531197965, 4.2864769591634575)

In [52]:
np.std(x), np.var(x)

(0.9343687096356638, 0.8730448855462153)

In [53]:
x[5] = np.nan # Set 5-elmt of x to be NaN ("not a number")
np.mean(x) # and now the mean fails-- operation on a nan results in another nan.

nan

In [54]:
np.nanmin(x), np.nanmax(x), np.nanstd(x), np.nanvar(x) # Tell numpy to drop NaNs.

(-1.982811806043661,
 2.3036651531197965,
 0.9285124983447184,
 0.8621354595823507)

In [56]:
import scipy.stats
x = np.random.normal(0, 1, 20 )
scipy.stats.kstest(x, 'norm') # 'norm' specifies normal distribution. Can also pass our own distribution function.

KstestResult(statistic=0.24184512726531485, pvalue=0.16290585320247297)

In [61]:
A = np.reshape( np.arange(1,13), (3,4) )
x = np.ones(4)
A*x

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [62]:
y = np.ones(3)
A*y

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [63]:
np.reshape(y, (3,1))*A

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [64]:
A = np.matrix(np.reshape(np.arange(1,13),(3,4)))
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [65]:
x = np.ones((4,1))
A*x

matrix([[10.],
        [26.],
        [42.]])

In [66]:
y = np.ones((1,3))
y*A

matrix([[15., 18., 21., 24.]])

In [68]:
x = range(10)
x**2

TypeError: unsupported operand type(s) for ** or pow(): 'range' and 'int'

In [71]:
[t**2 for t in np.arange(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [72]:
x = np.arange(10)
x**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
charray = np.array([x for x in 'Go Badgers']).reshape( (2,5) )
print( charray )

[['G' 'o' ' ' 'B' 'a']
 ['d' 'g' 'e' 'r' 's']]


In [75]:
np.sort( charray )

array([[' ', 'B', 'G', 'a', 'o'],
       ['d', 'e', 'g', 'r', 's']], dtype='<U1')

In [76]:
np.sort( charray, axis=1 )

array([[' ', 'B', 'G', 'a', 'o'],
       ['d', 'e', 'g', 'r', 's']], dtype='<U1')

In [77]:
np.sort( charray, axis=0 )

array([['G', 'g', ' ', 'B', 'a'],
       ['d', 'o', 'e', 'r', 's']], dtype='<U1')

In [78]:
np.sort( charray, axis=None )

array([' ', 'B', 'G', 'a', 'd', 'e', 'g', 'o', 'r', 's'], dtype='<U1')

In [79]:
print( charray )

[['G' 'o' ' ' 'B' 'a']
 ['d' 'g' 'e' 'r' 's']]
